In [3]:
import pandas as pd 
import numpy as np

In [4]:
#Initialise a dataframe to Full.csv in data folder
df = pd.read_csv('Data/Full.csv')

In [13]:
# Drop all columns that contain the string "Unnamed" in their name
df = df.drop(df.filter(regex='Unnamed').columns, axis=1)

In [14]:
df

,Sl. No.,Patent Application No.,Status of Patent (Published / Granted),Inventor/s Name,Title of the Patent,Applicant/s Name,Patent Filed Date (DD/MM/YYYY),Patent Published Date / Granted Date (DD/MM/YYYY),Patent Publication Number / Patent Granted Number,Assignee/s Name (Institute Affiliation/s at time of Appication),"Here, attach Source Proof Screenshots/URL/ Website Links, etc.",Department,Country,MAapping with SDG,Link of SDG Document
0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2315/MUM/2011,Granted,Dr. Prasad D. Khandekar,Pass Transistor Adiabatic Circuit With Stand- ...,Dr. Prasad D. Khandekar,17-08-2011,17-12-2020,353941,Vishwakarma Institute of Information Technolog...,https://drive.google.com/file/d/1k_mzGREKOL4uP...,Electrical and Electronics Engineering,India,"7,9,11,12,13",https://docs.google.com/document/d/16KGjPIDijs...
2,2.0,202021008633,Granted,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",Loop device for a plurality of teeth,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",28-02-2020,27-11-2020,352515,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1pAAiPHddW_vaK...,Mechanical Engineering,India,"3,9,10,12",https://docs.google.com/document/d/1M9fkxE7w2m...
3,3.0,2183/MUM/2012,Granted,"Vivek Deshpande, Archana Khandekar(Dhoke)",Process for estimation of flow rate to control...,Vivek Deshpande,7/31/2012,22-06-2020,339009,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1YLRIo1pGA6gZg...,Computer Engineering & Technology,India,"9,12,7,11,13",https://docs.google.com/document/d/1X4gQlJoRGN...
4,4.0,2020102377,Granted,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",Water collection & notification intelligent ma...,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",23-09-2020,10/21/2020,2020102377,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1nZIbix1oDSneW...,Civil Engineering,Australia,"6,7,9,11,12,13,17",https://docs.google.com/document/d/17UAsRzMoPR...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_2020 = df.iloc[1:25,:]

In [16]:
df_2020

,Sl. No.,Patent Application No.,Status of Patent (Published / Granted),Inventor/s Name,Title of the Patent,Applicant/s Name,Patent Filed Date (DD/MM/YYYY),Patent Published Date / Granted Date (DD/MM/YYYY),Patent Publication Number / Patent Granted Number,Assignee/s Name (Institute Affiliation/s at time of Appication),"Here, attach Source Proof Screenshots/URL/ Website Links, etc.",Department,Country,MAapping with SDG,Link of SDG Document
1,1.0,2315/MUM/2011,Granted,Dr. Prasad D. Khandekar,Pass Transistor Adiabatic Circuit With Stand- ...,Dr. Prasad D. Khandekar,17-08-2011,17-12-2020,353941,Vishwakarma Institute of Information Technolog...,https://drive.google.com/file/d/1k_mzGREKOL4uP...,Electrical and Electronics Engineering,India,"7,9,11,12,13",https://docs.google.com/document/d/16KGjPIDijs...
2,2.0,202021008633,Granted,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",Loop device for a plurality of teeth,"TIWARI, Meenakshi M.; JADHAV, Vikrant V.; THOT...",28-02-2020,27-11-2020,352515,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1pAAiPHddW_vaK...,Mechanical Engineering,India,"3,9,10,12",https://docs.google.com/document/d/1M9fkxE7w2m...
3,3.0,2183/MUM/2012,Granted,"Vivek Deshpande, Archana Khandekar(Dhoke)",Process for estimation of flow rate to control...,Vivek Deshpande,7/31/2012,22-06-2020,339009,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1YLRIo1pGA6gZg...,Computer Engineering & Technology,India,"9,12,7,11,13",https://docs.google.com/document/d/1X4gQlJoRGN...
4,4.0,2020102377,Granted,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",Water collection & notification intelligent ma...,"Jeevan Pise, Priya; Kamble, Sachin Ramchandra;...",23-09-2020,10/21/2020,2020102377,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1nZIbix1oDSneW...,Civil Engineering,Australia,"6,7,9,11,12,13,17",https://docs.google.com/document/d/17UAsRzMoPR...
5,5.0,2020101867,Granted,"Dr. Krishna Warhade, C.T., MANIMEGALAI; R., RA...",Design and Implementation of a disaster manage...,"C.T., MANIMEGALAI; R., RAJU; S., RAMESH; N., V...",18-08-2020,9/9/2020,2020101867,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/17qQt5wfX37pRa...,Electrical and Electronics Engineering,Australia,"11,9,13,3,17,7",https://docs.google.com/document/d/1ihmFAQRanW...
6,6.0,202021024989,Published,"Dr Atul Prabhakar Kulkarni, Dr Pravin Popat Hu...",Design and development of innovative spatters ...,Dr Pravin Popat Hujare,15-06-2020,10-07-2020,28/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1MgfkiElFe_9b4...,Mechanical Engineering,India,"9,12,8,13,11",https://docs.google.com/document/d/10D09X06aH7...
7,7.0,202021007685,Published,"SUCHITRA AMOL KHOJE, SANJAY BHAGWAN MOHITE",Safety System For Drainage Gas Monitoring,"SUCHITRA AMOL KHOJE, SANJAY BHAGWAN MOHITE",24-02-2020,3/6/2020,10/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/17Gl7DmYYHl9Ze...,Electrical and Electronics Engineering,India,"3,8,9,11,12,13",https://docs.google.com/document/d/1Y2lh9iqbf_...
8,8.0,202021007681,Published,"SANJAY BHAGWAN MOHITE, SUCHITRA AMOL KHOJE",Smart Crop Disease Detection And Treatment System,"SANJAY BHAGWAN MOHITE, SUCHITRA AMOL KHOJE",24-02-2020,3/6/2020,10/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1xrD_xK10rqSdY...,Electrical and Electronics Engineering,India,"2,9,12,13,8,15",https://docs.google.com/document/d/1cgevnyt5es...
9,9.0,202021043072,Published,Dr Mrudula S Kulkarni,Development of Thermal conductivity and maturi...,Dr Sumant N Shinde Dr. H. R. MagarPatil,04-10-2020,09-10-2020,41/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1SL1UhMbtlJfRU...,Civil Engineering,India,"9,11,12,13,7,4",https://docs.google.com/document/d/1gxiZPsfXk5...
10,10.0,201921053124,Published,"Prafulla Bansod, Ravindra Gaikwad, Shyam Kodape",Two Layer membrane Model for separation of Car...,"Shrikant Barkade, Dinesh Bhutada, Prafulla Ban...",20-12-2019,03-01-2020,01/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/11bQoA5xWGvfJa...,Chemical Engineering,India,"3,7,9,12,13,15,2",https://docs.google.com/document/d/1jAcZJAP_Gr...
11,11.0,202021034153,Published,"Aditya Sanjay Mhaske, Atharv Satish Nikam, San...",Smart glasses for monocular vision,"Aditya Sanjay Mhaske, Atharv Satish Nikam, San...",10-08-2020,8/21/2020,34/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/13xxOToZxZV2Xy...,Computer Engineering & Technology,India,"3,8,9,10,11,4,12",https://docs.google.com/document/d/1OQuHduwGOY...
12,12.0,202021030782,Published,"Shalaka Vardhaman Tiwatane, Vardhaman Pitambar...",DESIGN AND DEVELOPMENT OF PUBLIC ROAD TRANSPOR...,"Shalaka Vardhaman Tiwatane, Vardhaman Pitambar...",20-07-2020,28-08-2020,35/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1BWYIexWF6xWmV...,Computer Engineering & Technology,India,"3,11,8,9,10,12,17",https://docs.google.com/document/d/1zFjCyaaQ22...
13,13.0,202021040241,Published,"Mr. Vivekanand A Naikwadi, Dr.Amit Jomde, Mr.T...",Design and development of innovative radiator ...,"Mr. Vivekanand A Naikwadi, Dr.Amit Jomde, Mr.T...",17-09-2020,25-09-2020,39/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1-oUStQWMZXrus...,Mechanical Engineering,India,"9,12,13,8,3,7",https://docs.google.com/document/d/1QVjqFtZxWZ...
14,14.0,201921051720,Published,"Harshita Bhorshetti, Shreyas Ghuge, Sukhada Bh...",SMART GLASSES FOR THE VISUALLY IMPAIRED PEOPLE,"Harshita Bhorshetti, Shreyas Ghuge, Sukhada Bh...",13-12-2019,03-01-2020,01/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1O2jf2SA-G_4XY...,Electrical and Electronics Engineering,India,"3,10,9,8,4,11",https://docs.google.com/document/d/1_TAxoaBAjl...
15,15.0,202021033067,Published,"Dr Pravin Popat Hujare, Mr.Manas Anand Kulkarn...",Design and development of compact aloe vera ge...,"Dr Pravin Popat Hujare, Dr.Deepak Popat Hujare...",01-08-2020,28-08-2020,35/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/175h2gVunG0qdl...,Mechanical Engineering,India,"9,12,2,8,15,3",https://docs.google.com/document/d/1KlugFQb4bO...
16,16.0,201821029070,Published,"MS. MUSKAN PARAKH, MR. OMKAR KUMBHAR, DR. G. S...",ATC-SYSTEM: ADVANCED TRAFFIC CONTROL SYSTEM BY...,"MS. MUSKAN PARAKH, MR. OMKAR KUMBHAR, DR. G. S...",02-08-2018,2/7/2020,06/2020,"JSPM, Pune",https://drive.google.com/file/d/1e_h37DBnHJG3d...,Civil Engineering,India,"11,9,3,16,13",https://docs.google.com/document/d/1pDfDnzZIwe...
17,17.0,201921053887,Published,"Mrunal N Annadate, Manoj S. Nagmode",Method For Detection Of Heart Abnormality In U...,"Mrunal N Annadate, Manoj S. Nagmode",26-12-2019,21-02-2020,08/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1MOSVfxF13-HfU...,Electrical and Electronics Engineering,India,"3,8,10,12,17",https://docs.google.com/document/d/1NztlaGyuvb...
18,18.0,201921051414,Published,"Aditi Jahagirdar, Manoj Nagmode",SYSTEM AND METHOD FOR ABNORMAL EVENT DETECTION,"Aditi Jahagirdar, Manoj Nagmode",12-12-2019,31-01-2020,05/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1du10e7q6Ajdzb...,Computer Engineering & Technology,India,"3,9,11,16,17",https://docs.google.com/document/d/1CtD94cvSUz...
19,19.0,202041039531,Published,"Anita Nene, S. RAMACHANDRAN",Convex conical receiver with rim in concentrat...,"Anita Nene, S. RAMACHANDRAN",9/12/2020,9/25/2020,39/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1OEr17fyReqFm3...,Mechanical Engineering,India,"7,9,12,13",https://docs.google.com/document/d/1Ci53sO_WDr...
20,20.0,201821031879,Published,"Virendra V. Shete, Sunil B. Somani, Mangesh Gi...",System for multiple-fault diagnosis in digital...,"Mangesh Girish Islampurkar, Virendra V. Shete",25-08-2018,28-02-2020,09/2020,Dr.Vishwanath Karad MIT WORLD PEACE UNIVERSITY...,https://drive.google.com/file/d/1FNs1st7jECFgf...,Electrical and Electronics Engineering,India,"9,12,13,17",https://docs.google.com/document/d/1x_ziJjGRWl...
21,21.0,202021039556,Published,"Mahesh B. Sonawane, Sumedh Y. Mhaske\r\n",ADIM- CLIMATE ZONE OF INDIA: ASSESSMENT OF DAY...,"Mahesh B. Sonawane, Sumedh Y. Mhaske",9/13/2020,9/25/2020,39/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1FN14IrPGNVfvV...,Civil Engineering,India,"7,11,13,12",https://docs.google.com/document/d/1yjUUxzzV1o...
22,22.0,202021008223,Published,"Vandana Jagtap, Shilpa Pimpalkar, Kumudini Mun...",IOT Based Water Dispensing Apparatus,"Vandana Jagtap, Shilpa Pimpalkar, Kumudini Mun...",2/26/2020,5/22/2020,21/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1Y1bjfDRS79DjE...,Computer Engineering & Technology,India,"6,9,12,13,11",https://docs.google.com/document/d/13T-WUCjcfT...
23,23.0,201921002719,Published,"Swati Changdeo Jagdale, Anuruddha Rajaram Chab...",Stable topical composition comprising tretinoi...,"Swati Changdeo Jagdale, Anuruddha Rajaram Chab...",1/23/2019,7/31/2020,31/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1Ju4Nna2BEWbyw...,School of Pharmacy,India,NaN,NaN
24,24.0,201921019148,Published,"Choudhari Ganesh, Choudhari Vishnu, Kuchekar B...",Liquid Composition Comprising Multiple Active ...,"Choudhari Ganesh, Choudhari Vishnu, Kuchekar B...",5/14/2019,12/4/2020,49/2020,Dr. Vishwanath Karad MIT-World Peace University,https://drive.google.com/file/d/1iz9cRcis2Lg_f...,School of Pharmacy,India,NaN,NaN